In [1]:
import pandas as pd

df = pd.read_csv("lifestyle weight tracker copy.csv")

In [ ]:
print(df)

In [3]:
df.head()

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
1,296,43,Female,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,NaN,0,36.987432,0.211877,109.911211
2,125,47,Male,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,Yoga,10,35.977033,0.122390,111.082676
3,167,42,Female,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,Cardio,10,33.141805,0.308449,85.854547
4,311,54,Male,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,NaN,0,19.065076,0.120221,135.830726

In [4]:
df.tail()

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
54995,288,31,Female,172.989751,130.257318,6,5.791148,271.088251,2268.846150,141.8,255.2,75.6,7935,NaN,0,20.023635,0.175921,151.356362
54996,159,37,Male,179.688824,123.132106,9,7.691768,315.457575,1845.442138,115.3,207.6,61.5,7949,NaN,0,18.972702,0.175562,139.965519
54997,385,19,Female,167.302095,99.227392,3,8.340457,125.622338,NaN,150.0,269.9,80.0,7909,NaN,0,16.169056,0.113811,117.888421
54998,570,20,Male,178.401840,106.253039,10,5.833022,386.287965,2407.771582,150.5,270.9,80.3,7897,NaN,0,33.360536,0.340965,128.880845
54999,565,23,Male,175.664016,102.207143,10,10.402248,405.843037,1802.206215,112.6,202.7,60.1,7883,Strength,5,24.044327,0.215855,121.934377

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55000 entries, 0 to 54999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            55000 non-null  int64
 1   Age                55000 non-null  int64
 2   Gender             55000 non-null  str
 3   Height_cm          55000 non-null  float64
 4   Initial_Weight_kg  55000 non-null  float64
 5   Stress_Level       55000 non-null  int64
 6   Sleep_Hours        55000 non-null  float64
 7   Caffeine_mg        55000 non-null  float64
 8   Calories_Consumed  52250 non-null  float64
 9   Protein_g          55000 non-null  float64
 10  Carbs_g            55000 non-null  float64
 11  Fat_g              55000 non-null  float64
 12  Steps              55000 non-null  int64
 13  Workout_Type       27448 non-null  str
 14  Workout_Intensity  55000 non-null  int64
 15  Temp_C             55000 non-null  float64
 16  Weight_Change      55000 non-null  float64
 17  Current_Weight_kg  55000 non-null  float64
dtypes: float64(11), int64(5), str(2)
memory usage: 7.6 MB

In [8]:
df.describe()

,User_ID,Age,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
count,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,52250.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000,55000.000000
mean,349.441400,40.918545,169.972335,114.999924,5.524964,6.666340,261.091734,2097.729693,131.073911,235.932955,69.906169,7999.830891,3.496091,24.998172,0.168459,124.480910
std,144.343054,13.539751,9.991794,17.291936,2.881427,1.543146,114.579046,601.919105,37.583689,67.650694,20.044495,89.285148,3.776365,7.992403,0.105259,18.257341
min,100.000000,18.000000,126.190233,85.000325,1.000000,3.000000,0.000000,-327.404484,-20.500000,-36.800000,-10.900000,7632.000000,0.000000,-6.075821,-0.250723,85.327609
25%,224.000000,29.000000,163.273360,100.032148,3.000000,5.610998,181.968341,1693.339924,105.800000,190.500000,56.400000,7939.000000,0.000000,19.609512,0.096170,109.458941
50%,350.000000,41.000000,169.984098,115.032495,6.000000,6.659498,260.645919,2095.328161,130.900000,235.600000,69.800000,7999.000000,0.000000,24.996455,0.168383,124.555885
75%,474.000000,53.000000,176.675947,129.899387,8.000000,7.714812,339.196616,2501.645667,156.300000,281.325000,83.400000,8060.000000,7.000000,30.411654,0.241079,139.369026
max,599.000000,64.000000,213.837588,144.998228,10.000000,11.000000,740.175153,4874.404173,304.700000,548.400000,162.500000,8365.000000,10.000000,58.914302,0.593711,291.842383

In [10]:
df.index

RangeIndex(start=0, stop=55000, step=1)

In [11]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Height_cm', 'Initial_Weight_kg',
       'Stress_Level', 'Sleep_Hours', 'Caffeine_mg', 'Calories_Consumed',
       'Protein_g', 'Carbs_g', 'Fat_g', 'Steps', 'Workout_Type',
       'Workout_Intensity', 'Temp_C', 'Weight_Change', 'Current_Weight_kg'],
      dtype='str')

In [16]:
df[['Age', 'Workout_Type']]

       Age Workout_Type
0       23     Strength
1       43          NaN
2       47         Yoga
3       42       Cardio
4       54          NaN
...    ...          ...
54995   31          NaN
54996   37          NaN
54997   19          NaN
54998   20          NaN
54999   23     Strength

[55000 rows x 2 columns]

In [23]:
# Returns a new DataFrame with no NaNs
df_cleaned = df.dropna()